### ISSUE TITLE
Curators need to be able to cross reference between different sources of information about submissions

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#146]
Curators need a way of cross referencing between different sources of information about submissions in order to contact submitters via email and publicise submissions via twitter, following each data release. 

The weekly submissions report needs to contain:
- An active link to the GCP in the deposition app 
- The first author of each publication or body of work
- The PMID (currently only included the first time the submission appears in the weekly report)

**Comment by ljwh2** [comment]
@earlEBI @mcerezof please confirm this meets your requirements

**Comment by earlEBI** [comment]
confirmed from me.

**Comment by tudorgroza** [comment]
@ljwh2 @mcerezof @eks-ebi - this is now deployed in PROD. You should receive the new format with Sunday's report.

**Comment by earlEBI** [comment]
@tudorgroza  Looks good, but hyperlinks 'submission' and 'GCP' hyperlinks are broken.

**Comment by tudorgroza** [comment]
@earlEBI - would you be so kind to forward me the email? Thank you!

**Comment by tudorgroza** [comment]
I've fixed the URL and had a go at removing the new line before the closing bracket. Will push to production tomorrow, but the report will be there only next Sunday.

**Comment by ljwh2** [comment]
@tudorgroza Looks like the new version still does not include first author as described in the original ticket, please could you add this? (first author is not always the same as the submitter)

**Comment by tudorgroza** [comment]
@ljwh2 - I've checked the last weekly digest and for body of works submissions the first authors are included correctly (unfortunately, the formatting doesn't really help - I hope I've fixed it with the last changes). For publication submissions, on the other hand, something's wrong. Working on fixing it now.

**Comment by tudorgroza** [comment]
Fixed. Will deploy tomorrow morning.
