### ISSUE TITLE
Add user submission study to the database - GCP000742

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#1550]
User submission from 2023. Contacted by user Jan 2025. 

1 study 'GCST90296666'. Not on staging. 

Found in original Globus folder and moved manually to staging and public FTP, but the study needs to be added to the database. 

Please add to database and create yaml.

**Comment by karatugo** [comment]
fixed file type

**Comment by karatugo** [comment]
yaml should be generated tonight

**Comment by karatugo** [comment]
yaml is generated in ftp staging, waiting for ftp sync

**Comment by karatugo** [comment]
ftp sync failed due to node failure on codon, restarted yesterday.

**Comment by karatugo** [comment]
@earlEBI  Please confirm https://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90296001-GCST90297000/GCST90296666/

**Comment by earlEBI** [comment]
@karatugo Thanks. Only the data file name doesn't look right: 
# Summary Statistic information
data_file_name: \.tsv.gz

And case control numbers aren't shown, for some reason. 

But else generally okay.

**Comment by karatugo** [comment]
Fixed file path data in Mongodb. YAML will be generated today.

**Comment by earlEBI** [comment]
filename is now correct. I still don't know why case control numbers aren't shown, but overall okay.

**Comment by ljwh2** [comment]
@earlEBI we will close this ticket for now and please create another for the case control numbers

**Comment by earlEBI** [comment]
created ticket #[1581](https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1581)
