### ISSUE TITLE
Summary statistics page does not load in Chrome for several users

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#828]

**Comment by ljwh2** [comment]
Note, this was working for me until I updated Chrome to the latest version (Version 104.0.5112.79), now it does not work.

**Comment by ljwh2** [comment]
I also noticed the documentation pages were slow to load in Chrome, but this seems to be now resolved

**Comment by ljwh2** [comment]
This is due to inefficient pagination. We can change the pagination to work from the back end, but this will stop the search functionality working correctly. 

Important functionality for the published studies table search (in order of priority) is:
1. Sort by Publication date - this allows the user to find the most recently added sumstats. Alternatively the table could be loaded pre-sorted by publication date.
2. Filter by First author - the main search bar does not do this efficiently
3. Filter by trait and reported trait - this would be better done in the main search bar which is ontology driven. However users are hampered by the page loading for traits with many associations or child terms, if all they want is the sumstats. 
3. Filter by PMID, GCST - these can be easily done in the main search bar, but this table allows users to get to the sumstats in fewer clicks. 

Important functionality for the unpublished studies table search is:
1. Sort by Date Submitted 
2. Filter by First author
3. Filter by Reported trait
4. Filter by Study accession (lower priority)

Search functionality is more important for unpublished than published, as unpublished study metadata is not indexed in the main search.

**Comment by sprintell** [comment]
@ljwh2  This is solved now with the immediate solution proposed, someone can help confirm in snoopy

http://gwas-snoopy.ebi.ac.uk:9780/gwas/downloads/summary-statistics

**Comment by ljwh2** [comment]
Tested in Snoopy, published studies table had still not loaded after 5 mins. Prod version in Firefox loads in <30s.

**Comment by ljwh2** [comment]
This now works for me, but we need to make sure the table is pre-sorted by publication date so the most recent studies are displayed
